### ISSUE TITLE
how do i make the funny note stopping effect like in Die Batsards?

### ISSUE THREAD

**Issue by silvashp** [nebulazorua/andromeda-engine#99]
https://www.youtube.com/watch?v=gA5x-iK2DdI&t=70s&ab_channel=RainyCobra
1:00

**Comment by RealGuyWhoIsReal** [comment]
in the chart .json files for andromeda there's an optional sliderVelocities thing that can be put in the beginning of the chart like this

{
	"sliderVelocities": [
		{
	],
	"song": {
		"player1":......

to make the stopping effect Die Batsards uses some weird shit I don't understand because I'm not a programmer, but you can easily recreate the effect by doing this

{
	"sliderVelocities": [
		{
			"startTime": 0,
			"multiplier": 1 (or any that you wanted to use)
		},
			"startTime": [the time when the stop effect starts; every second equals 100],
			"multiplier": 1.38777878078145e-16
		},
		{
			"startTime": [the time when the stop effect stops],
			"multiplier": 1 (or any that you wanted to use)
		}
	],
	"song": {
		"player1":......

this is how a working version of the effect would look like on Fresh

{
    "sliderVelocities": [
		{
			"startTime": 0,
			"multiplier": 1
		},
		{
			"startTime": 880,
			"multiplier": 1.38777878078145e-16
		},
		{
			"startTime": 1000,
			"multiplier": 1
		},
		{
			"startTime": 1500,
			"multiplier": 1.38777878078145e-16
		},
		{
			"startTime": 1610,
			"multiplier": 1
		}
	],
	"song": {
		"player1": "bf",.....

the way you should use it is put the first scroll stop at the time first note is pressed, the second one should be some time before the second note that unfreezes scroll speed, like a square or two in the chart mode
just experiment and you'll figure it out idk

here's the fresh chart if you wanna see how this shit works
[fresh-hard.txt](https://github.com/nebulazorua/andromeda-engine/files/8806204/fresh-hard.txt)
(.json files are not allowed so you'll have to put the shit inside the .txt file into one)

if it doesn't work then either you are or i am a dumbass
